#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

WRANGLER_CONFIG="wrangler.jsonc"
UUID_RE='[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'

# extract_uuid TEXT prints the first UUID found in TEXT, or nothing. Wrangler
# prints the new database_id in both `d1 create` and `d1 info` output.
extract_uuid() {
  local found
  found=$(grep -oiE "$UUID_RE" <<<"$1" | head -n1) || true
  printf '%s' "$found"
}

# record_db_id ENV ID writes ID into the database_id slot of the env.<ENV>
# block in wrangler.jsonc, replacing whatever is there now (the placeholder,
# or an old id on a re-run). Scoped to the block by its database_name so the
# three identical placeholders don't collide.
record_db_id() {
  local env="$1" id="$2"
  perl -0pi -e "s/(\"database_name\":\s*\"dreamport-${env}\",\s*\n\s*\"database_id\":\s*)\"[^\"]*\"/\${1}\"${id}\"/" \
    "$WRANGLER_CONFIG"
  if grep -q "\"${id}\"" "$WRANGLER_CONFIG"; then
    printf '  %s✓ recorded%s dreamport-%s → %s in %s\n' \
      "$GREEN" "$RESET" "$env" "$id" "$WRANGLER_CONFIG"
  else
    warn "could not write the id into $WRANGLER_CONFIG automatically."
    note "Edit the env.${env} block by hand: set database_id to ${id}"
  fi
}

# provision_db ENV creates (or looks up) the dreamport-<ENV> D1 database and
# records its id. Safe to re-run: an existing database is looked up, not
# recreated.
provision_db() {
  local env="$1" name="dreamport-$1" out="" id=""

  say "Database: ${BOLD}${name}${RESET}"
  if ! confirm "Create or look up ${name} with wrangler now?"; then
    ask MANUAL_ID "Paste the database_id for ${name} (or Enter to skip):"
    if [[ -n "${MANUAL_ID:-}" ]]; then
      record_db_id "$env" "$MANUAL_ID"
    else
      SKIPPED+=("record database_id for ${name}")
    fi
    return 0
  fi

  step "Running: npx wrangler d1 create ${name}"
  out=$(npx wrangler d1 create "$name" 2>&1) || true
  id=$(extract_uuid "$out")

  if [[ -z "$id" ]]; then
    note "Create didn't return an id (the database may already exist)."
    step "Running: npx wrangler d1 info ${name}"
    out=$(npx wrangler d1 info "$name" 2>&1) || true
    id=$(extract_uuid "$out")
  fi

  if [[ -z "$id" ]]; then
    warn "Couldn't determine the database_id automatically. Wrangler said:"
    printf '%s\n' "$out" | sed 's/^/    /'
    open_url "https://dash.cloudflare.com/?to=/:account/workers/d1"
    step "Open ${name} in the dashboard and copy its Database ID."
    ask MANUAL_ID "Paste the database_id for ${name}:"
    id="${MANUAL_ID:-}"
  fi

  if [[ -n "$id" ]]; then
    record_db_id "$env" "$id"
  else
    SKIPPED+=("record database_id for ${name}")
  fi
}

banner "Dreamport: D1 databases & environment setup"

# ── Stage 1 ──────────────────────────────────────────────────────────────
stage "Prerequisites"
say "This wizard creates the three Cloudflare D1 databases Dreamport deploys"
say "against and records their IDs in ${WRANGLER_CONFIG}."
note "You need: a Cloudflare account with Workers & D1 enabled, and access to"
note "the account that owns (or will own) the dreamport-* Workers."
say ""
say "Wrangler is already installed as a dev dependency; this uses 'npx wrangler'."
note "Database IDs are NOT secrets — the edits to ${WRANGLER_CONFIG} are meant"
note "to be committed. No secrets are written by this wizard."
pause "Ready?"

# ── Stage 2 ──────────────────────────────────────────────────────────────
stage "Authenticate Wrangler"
say "A browser window will open for you to authorize Wrangler against your"
say "Cloudflare account."
if npx wrangler whoami 2>/dev/null | grep -qi "logged in"; then
  note "Already logged in:"
  npx wrangler whoami 2>/dev/null | sed 's/^/    /' || true
  confirm "Use this account?" || { step "Running: npx wrangler logout"; npx wrangler logout || true; npx wrangler login; }
else
  step "Running: npx wrangler login"
  npx wrangler login
fi
step "Confirming the active account:"
npx wrangler whoami 2>/dev/null | sed 's/^/    /' || true
pause "Right account?"

# ── Stage 3 ──────────────────────────────────────────────────────────────
stage "Production database (dreamport-prod)"
provision_db prod

# ── Stage 4 ──────────────────────────────────────────────────────────────
stage "Staging database (dreamport-stage)"
say "Per-PR preview deployments bind to this database, never to production."
provision_db stage

# ── Stage 5 ──────────────────────────────────────────────────────────────
stage "Remote dev database (dreamport-dev)"
say "Opt-in remote D1 for database-heavy testing before opening a PR."
say "Local 'npm run dev' keeps using Miniflare's local SQLite regardless."
provision_db dev

# ── Stage 6 ──────────────────────────────────────────────────────────────
stage "Set up the two Workers Builds projects"
say "Production and staging are two separate Workers Builds projects, both"
say "Git-connected to this repo, so each gets its own runtime secrets. The"
say "environment is chosen at build time via CLOUDFLARE_ENV, set inline in"
say "each project's Build command (not inferred from the branch, and not set"
say "as a separate Build variable — that panel has proven unreliable)."
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
step "Open (or create via 'Connect to Git') the 'dreamport' Worker, then:"
step "  Settings -> Build."
step "Set the Build command to:      CLOUDFLARE_ENV=production npm run build"
step "Set the production branch to:  main"
step "Uncheck 'Builds for non-production branches'."
step "Leave the Deploy command as:   npx wrangler deploy"
step "Save."
step "Now create a second Worker, 'dreamport-staging', connected to the same"
step "  repo, then: Settings -> Build."
step "Set the Build command to:      CLOUDFLARE_ENV=staging npm run build"
step "Set the production branch to a branch that is never pushed to (so"
step "  every real branch takes the preview path, never promote-to-live)."
step "Check 'Builds for non-production branches'."
step "Leave the Version command as:  npx wrangler versions upload"
step "Save."
note "docs/deployment.md has the full picture."
pause "Done (or noted to do later)?"
# ──────────────────────────────────────────────────────────────────────────

finish
note "Next:"
note "  1. Review the database_id edits:  git diff ${WRANGLER_CONFIG}"
note "  2. Commit them (they are not secrets)."
note "  3. Once migrations/ has SQL files (issue #20), apply them per env:"
note "       npm run migrate:staging   &&   npm run migrate:production"
note "See docs/deployment.md for the full procedure."
